### PR TITLE
Drop support for node v8

### PR DESCRIPTION
**Pull request by kaimallea**
- Update `engines` fields
- Remove node 8 from Travis config

### CODE REVIEW

**Comment by fastfrwrd** [comment]
should we trigger a release for this? e.g. should the `chore` be a `fix`

**Comment by kaimallea** [comment]
@fastfrwrd might be worth a release sooner rather than later, to prevent people who are stuck on `8`, for whatever reason, from thinking we support it

**Comment by kaimallea** [comment]
I can also amend `chore()` to `fix()`

**Comment by kaimallea** [comment]
👍 commit message amended (`chore` -> `fix`)

**Pull request merged**
