### PR TITLE
improvement(eslint-config-react): adds eslint-plugin-react-hooks plugin

### PR DESCRIPTION
**Pull request by braulio-balanza**
Adds the plugin to eslint-config-react-hooks and to the appropriate packages and test files.

#305

### CODE REVIEW

**Comment by fastfrwrd** [comment]
@braulio-balanza thanks for the PR! the test failure is due to a flaky test on our end, I'm addressing that and re-running your PR.

**Comment by fastfrwrd** [comment]
@braulio-balanza I was unable to re-run your PR; please rebase and push to your branch to get a clean re-run.

**Comment by braulio-balanza** [comment]
Yes, will do!

**Pull request merged**
